version: "3.3"

services:
  peertube-seeder:
    image: tyrsarm/peertube-headless-seeder:latest
    environment:
      peertube_url: "https://jupiter.tube/"
      retry_sec: 300
    restart: unless-stopped
